
# This workflow will build a Mule project with Maven.,
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: DEV Deployment 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set environment variables
env:

  # *************************************************************************************************************************************************************************
  # **************************************** DEVELOPERS ARE RESPONSIBLE IN MANAGING PARAMETERS BELOW THIS LINE **************************************************************
  # *************************************************************************************************************************************************************************

  # **************************** Cloudhub2.0 Deployment (Required only for Cloudhub2.0 deployment) **************************************************
  target: ""                                                                                # Private Space details of Cloudhub2.0

  # **************************************** MULE RUNTIME PROPERTIES ********************************************************************************************************  
  muleVersion: 4.4.0                                                                          				# Mule Version to be deployed - maps to app.runtime
  deploymentTimeout: 1000000                                                                  				# deployment timeout setting
  replicas: ${{ secrets.np_replicas }}                                                                      # No. of replicas required for high avialability and horizontal scaling
  vCores: ${{ secrets.np_vcore }}                                                                           # 0.1, 0.5, 1.5, 2.5, 3.5 and 4 vcores are the possible values
  clustered: "true"                                                                        					# The value will be true if clustering is needed and False for non clustered deployment 
  applicationName: "applicationName"                                                   					# Application Name in Runtime Manager. 
  businessGroupId: ${{ secrets.CHV2_BUSINESSGROUPID }}                                       				# Please configure the corresponding Businessgroup ID in which the app needs to be deployed in the secret from Anypoint platform team.
  publicUrl: "Add public URL"                                                                   # Please provide the common name configured for the non prod private space, please check with Mule admin team for details.
  objectStoreV2: "false"                                                                            # Please provide the value as true or false based on object store usage in your application  
  githubToken: ${{ secrets.GITHUBTOKEN }}                                                           # PAT stored in secrets to clone another repository
  splunk_host: "Add splunk host including port"                                      # Host name of the Splunk cloud instance
  splunk_token: ${{ secrets.SPLUNK_TOKEN }}                                                         # Splunk token  
  # **************************************** API MANAGER PROPERTIES **********************************************************************************************************
  apiId: ""                                                                           						# for Autodiscovery purpose. Must match API ID in API Manager 

  # **************************************** MULE APPLICATION PROPERTIES *****************************************************************************************************
  workflowEnv: "dev"                                                                            				# this maps to mule application {env} properties
  key: ${{ secrets.np_encryptdecryptkey }}                                                       			# Key to decrypt secure properties. Make sure to use AES algorithm 256 bits

  # **************************************** API VISUALIZER PROPERTIES (Required to be updated accurately by Mule Developers based on the APIs) ******************************
  apiLayer: "System"                                                                               				# Experience - experience API; Process - process API; System - system API
  apiTags:  ""                                       														# Tags to be configured in Anypoint Visualizer
  
  # **************************************** CUSTOM POM.XML XML TAG NAME CHANGE **********************************************************************************************
  # ****************************** IN MOST CASES, YOU DON'T NEED TO MAKE ADJUSTMENT ******************************************************************************************
  # Property names - in most cases these should not need adjustment from the defaults
  # These values should correspond to the XML tag defined in your POM file. What is XML tag? it is illustrated as: <xmlTag>${values}</xmlTag>
  # Only make changes here if you understand what you are doing!

  anypointPlatformBaseUriProperty: "anypointPlatformBaseUri"                                  # Name of the property that contains the Anypoint Base URI
  muleVersionProperty: "muleVersion"                                                          # Name of the property that contains the MuleSoft runtime version
  replicasProperty: "replicas"                                                                # Name of the property that contains the number of replicas similar to workers in current onpremise.
  vCoresProperty: "vCores"                                                                    # Name of the property that conains the number of vCores
  serverProperty: "server"                                                                    # Name of the property that contains the server name defined in settings.xml
  providerProperty: "provider"                                                                # Name of the property that contains the provider name
  lastMileSecurityProperty: "lastMileSecurity"                                                # Name of the property that contains the lastMileSecurity
  forwardSslSessionProperty: "forwardSslSession"                                              # Name of the property that contains the forwardSslSession
  clusteredProperty: "clustered"                                                              # Name of the property that contains the clustered
  updateStrategyProperty: "updateStrategy"                                                    # Name of the property that contains the updateStrategy
  anypointPlatformEnvProperty: "anypoint_platform_env"                                        # Name of the property that contains the Anypoint environment
  businessgroupIdProperty: "businessGroupId"                                                  # Name of the property that contains the Anypoint Business Group Id
  businessgroupOrgIdProperty: "businessGroupOrgId"                                            # Name of the property that contains the Anypoint Business Group Org Id
  anypointPlatformBusinessGroupProperty: "anypoint_platform_business_group"                   # Name of the property that contains the Anypoint Business Group Name
  envProperty: "env"                                                                          # Name of the property that selects the appropriate config files
  anypointPlatformClientIdProperty: "anypoint_platform_client_id"                             # Name of the property that contains the Anypoint Platform Client Id
  anypointPlatformClientSecretProperty: "anypoint_platform_client_secret"                     # Name of the property that contains the Anypoint Platform Client Secret
  keyProperty: "security.key"                                                                 # Name of the property that contains the security key to decrypt sensitive properties
  apiAutodiscoveryIdProperty: "api.autodiscoveryID"                                           # Name of the property that contains the API Autodiscovery Id
  apiLayerProperty: "apiLayer"                                                                # Name of the property that contains the Anypoint Visualizer API Layer
  apiTagsProperty: "apiTags"                                                                  # Name of the property that contains the Anypoint Visualizer Tags
  targetProperty: "target"                                                                    # Name of the property that contains the AWS target server
  deploymentTimeoutProperty: "deploymentTimeout"                                              # Name of the property that contains the Deployment timeout value
  publicUrlProperty: "publicUrl"                                                              # Name of the property that contains the publicUrl
  objectStoreV2Property: "objectStoreV2"                                                      # Name of the property that contains the object store v2
  splunkHostProperty: "splunk_host"                                                           # Name of the property that contains the splunk_host
  splunkTokenProperty: "splunk_token"                                                         # Name of the property that contains the splunk_token



# **************************************** DO NOT MAKE ANY CHANGES TO THIS SCRIPT BELOW THIS POINT ****************************************************


# CRITICAL PARAMETERS FOR DEV PARAMETERS
  anypointPlatformClientId: ${{ secrets.anypoint_platform_client_id_dev }}                    # Cloudhub Environment Client ID
  anypointPlatformClientSecret: ${{ secrets.anypoint_platform_client_secret_dev }}            # Cloudhub Environment Client Secret
  anypointPlatformBaseUri: https://anypoint.mulesoft.com/                                     # always https://anypoint.mulesoft.com/
  anypointPlatformUsername: ${{ secrets.ANYPOINT_CONNECTED_APP_USERNAME_NON_PROD }}           # Anypoint Platform Connected App Username for deployment
  anypointPlatformPassword: ${{ secrets.ANYPOINT_CONNECTED_APP_PASSWORD_NON_PROD}}            # Anypoint Platform Connected App Password for deployment
  anypointPlatformEnvName: "DEV"                                                          	  # Environment name of the deployment target environment (Case Sensitive)
  server: "anypoint-connected-app"                                                            # configured as server id in pom.xml so it should always be sent as anypoint-connected-app
  deploymentTarget: "Cloudhub2.0"                                                             # Value should always be Cloudhub2.0
  provider: "MC"                                                                              # Value should always be MC for Cloudhub2.0
  lastMileSecurity: "false"                                                                   # Value should always be false for Cloudhub2.0                                                               
  forwardSslSession: "false"                                                                  # Value should always be false for Cloudhub2.0
  updateStrategy: "rolling"                                                                   # Value should always be rolling for Cloudhub2.0 since we prefer zero downtime during the deployment
  
jobs:
  Build_and_deploy:
    runs-on: ubuntu-latest

    steps:
#******************************** Action to clone the multiple directory in the target path***********************************
    - uses: actions/checkout@v2
    
#********************************Action to setup JDK 1.8**********************************************************************   
    - name: Set up JDK 1.8 version
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set up Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        java-version: 8
        maven-version: 3.8.2
        
    #- uses: actions/checkout@v3
      #with:
        #repository: 'Deploy_mule'
        #token: ${{ env.githubToken }}
        #path: 'script'
        
#******************************Action to create the settings.xml by passing the necessary ids and URLs*******************************************
    - name: Create maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v9
      with:
        servers: '[{"id": "anypoint-connected-app", "username": "${{ secrets.ANYPOINT_CONNECTED_APP_USERNAME_NON_PROD }}", "password": "${{ secrets.ANYPOINT_CONNECTED_APP_PASSWORD_NON_PROD}}" },{"id": "MuleRepository", "username": "${{ secrets.MULE_ENT_USERNAME_NEXUS }}", "password": "${{ secrets.MULE_ENT_PASSWORD_NEXUS }}" }, {"id": "github", "username": "${{secrets.githubusername}}", "password": "${{secrets.githubtoken}}" }, {"id": "central", "username": "${{secrets.DDB_JFROG_USER}}", "password": "${{secrets.DDB_JFROG_PASSWORD}}"}]'
        repositories: '[{"id": "MuleRepository", "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"},{"id": "anypoint-exchange-v2", "url": "https://maven.anypoint.mulesoft.com/api/v2/maven"}]'

    - run: |
        cat ~/.m2/settings.xml                                 #To view the settings.xml
        
    - run: |
        mvn clean deploy -DskipMunitTests -DbusinessGroupId=${{ env.businessGroupId }}   # command to deploy the application in exchange as a mandatory step as per the Cloudhub V2
 
 #********************************************Maven script to deploy the jar to the target environment******************************************
    - name: Deploy to ${{ env.deploymentTarget }} 
      run: bash ${{ github.workspace }}/script/Maven/Maven_Deploy_dev.sh
